/* Generate D-Bus XML Introspection from .fidl file
 * v0.1
 * Based on Test.C generated by BNFC
 */
#include <stdio.h>
#include <iostream>
#include <fstream>
#include "Parser.H"
#include "Absyn.H"
#include "XMLGenerator.H"
#include "CustomTypesParser.H"

using namespace std;

int main(int argc, char ** argv)
{
  if (argv[1] == NULL) {
    fprintf(stderr, "Error: No .fidl file given.\n");
    exit(1);
  }

  FILE *input;
  std::string pathToImportFile = "";
  if (argc > 1) 
  {
    input = fopen(argv[1], "r");
    if (!input)
    {
      fprintf(stderr, "Error opening input file.\n");
      exit(1);
    }
    
    // To solve imports in the fidl file, we need to save the folder path.
    std::string tmp_pathToImportFile = argv[1];
    size_t posOfLastSlash = tmp_pathToImportFile.find_last_of("/");
    if (posOfLastSlash != std::string::npos) {
      pathToImportFile = tmp_pathToImportFile.substr(0, posOfLastSlash);
    }
    //cout << "Path to file name: " << pathToImportFile << endl;
    //cout << "Position of last /: " <<  posOfLastSlash << endl;
  } 
  else {
  input = stdin;
  }
  
  /* The default entry point is used. For other options see Parser.H */


  
  
  // Output file for D-Bus XML Introspection

  char* givenFile = argv[1];
  //  printf("%s \n", givenFile); 

  // If source file has the format XYZ.fidl, name the output file XYZ.xml
  // Otherwise, if it is called XYZ*, name it XYZ*.xml
  
  std::string outputFilename = givenFile;
  int found = outputFilename.rfind(".fidl");
  if (found != -1) {
    outputFilename.replace(found, 5, "");
  }
  outputFilename.append(".xml");
  
  ofstream output;
  output.open(outputFilename.c_str());
  

  Program *parse_tree = pProgram(input);
  if (parse_tree)
  {
  
    /* NOT USED FOR THIS PROJECT
    // #include "Printer.H" to use
    printf("\nParse Succesful!\n");
    printf("\n[Abstract Syntax]\n");
    ShowAbsyn *s = new ShowAbsyn();
    printf("%s\n\n", s->show(parse_tree));
    printf("[Linearized Tree]\n");
    PrintAbsyn *p = new PrintAbsyn();
    printf("%s\n\n", p->print(parse_tree));
    */
    
    
    
    // Generate XML file
    GenerateDBusXML *g2 = new GenerateDBusXML();
    g2->createCustomTypesList(parse_tree, pathToImportFile);
    output << g2->generate(parse_tree, pathToImportFile);
    output.close();
    cout << "Finished generating D-Bus XML Introspection to file " << outputFilename << ". File content: " << endl << endl;
    
    // Print generated file
    ifstream generatedFile(outputFilename.c_str());
    std::string templine;
    while (getline(generatedFile, templine)) {
        cout << templine << endl;
    }
    
    
    return 0;
  }
  return 1;
}

