/* Generate D-Bus XML Introspection from .fidl file
 * v0.1
 * Based on Test.C generated by BNFC
 */
#include <stdio.h>
#include <iostream>
#include <fstream>
#include "Parser.H"
#include "Printer.H"
#include "Absyn.H"
#include "XMLGenerator.H"

using namespace std;

int main(int argc, char ** argv)
{
  FILE *input;
  if (argc > 1) 
  {
    input = fopen(argv[1], "r");
    if (!input)
    {
      fprintf(stderr, "Error opening input file.\n");
      exit(1);
    }
  }
  else input = stdin;
  /* The default entry point is used. For other options see Parser.H */

  
  // Output file for D-Bus XML Introspection

  char* givenFile = argv[1];
  //  printf("%s \n", givenFile); 

  // If source file has the format XYZ.fidl, name the output file XYZ.xml
  // Otherwise, if it is called XYZ*, name it XYZ*.xml
  
  string outputFilename = givenFile;
  int found = outputFilename.rfind(".fidl");
  if (found != -1) {
    outputFilename.replace(found, 5, "");
  }
  outputFilename.append(".xml");
  ofstream output;
  output.open(outputFilename.c_str());
  
  //TODO

  Program *parse_tree = pProgram(input);
  if (parse_tree)
  {
    printf("\nParse Succesful!\n");
    printf("\n[Abstract Syntax]\n");
    ShowAbsyn *s = new ShowAbsyn();
    printf("%s\n\n", s->show(parse_tree));
    printf("[Linearized Tree]\n");
    PrintAbsyn *p = new PrintAbsyn();
    printf("%s\n\n", p->print(parse_tree));
    printf("[D-Bus XML Introspection]\n");
    GenerateDBusXML *g = new GenerateDBusXML();
    printf("%s\n\n", g->generate(parse_tree));
    //TODO
    output << g->generate(parse_tree);
    output.close();
    
    
    return 0;
  }
  return 1;
}

