/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core Unknown.
* Used org.franca.core Unknown.
*
* 
*/
#ifndef ORG_GENIVI_MEDIAMANAGER_Indexer_H_
#define ORG_GENIVI_MEDIAMANAGER_Indexer_H_


#include <org/genivi/mediamanager/MediaTypes.h>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/types.h>
#include <cstdint>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace org {
namespace genivi {
namespace mediamanager {

class Indexer {
 public:
    virtual ~Indexer() { }

    static inline const char* getInterfaceId();
    static inline CommonAPI::Version getInterfaceVersion();
    typedef MediaTypes::BackendError IndexerError;
};

const char* Indexer::getInterfaceId() {
    static const char* interfaceId = "org.genivi.mediamanager.Indexer";
    return interfaceId;
}

CommonAPI::Version Indexer::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace mediamanager
} // namespace genivi
} // namespace org

namespace CommonAPI {

}


namespace std {
    //hashes for types

    //hashes for error types
}

#endif // ORG_GENIVI_MEDIAMANAGER_Indexer_H_
