/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core Unknown.
* Used org.franca.core Unknown.
*
* 
*/
#ifndef ORG_GENIVI_MEDIAMANAGER_Indexer_STUB_DEFAULT_H_
#define ORG_GENIVI_MEDIAMANAGER_Indexer_STUB_DEFAULT_H_


#include <org/genivi/mediamanager/IndexerStub.h>
#include <sstream>

namespace org {
namespace genivi {
namespace mediamanager {

/**
 * Provides a default implementation for IndexerStubRemoteEvent and
 * IndexerStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class IndexerStubDefault : public virtual IndexerStub {
public:
    IndexerStubDefault();

    IndexerStubRemoteEvent* initStubAdapter(const std::shared_ptr<IndexerStubAdapter>& stubAdapter);

    const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> clientId);

    virtual const Indexer::IndexerStatus& getIndexerStatusAttribute();
    virtual const Indexer::IndexerStatus& getIndexerStatusAttribute(const std::shared_ptr<CommonAPI::ClientId> clientId);
    virtual void setIndexerStatusAttribute(Indexer::IndexerStatus value);

    virtual void getDatabasePath(const std::shared_ptr<CommonAPI::ClientId> clientId, std::string& output, Indexer::IndexerError& e);
    virtual void getDatabasePath(std::string& output, Indexer::IndexerError& e);

    virtual void stopIndexing(const std::shared_ptr<CommonAPI::ClientId> clientId, Indexer::IndexerError& e);
    virtual void stopIndexing(Indexer::IndexerError& e);

    virtual void startIndexing(const std::shared_ptr<CommonAPI::ClientId> clientId, Indexer::IndexerError& e);
    virtual void startIndexing(Indexer::IndexerError& e);




protected:
    /**
     * Example comment
     */
    virtual bool trySetIndexerStatusAttribute(Indexer::IndexerStatus value);
    virtual bool validateIndexerStatusAttributeRequestedValue(const Indexer::IndexerStatus& value);
    class RemoteEventHandler: public virtual IndexerStubRemoteEvent {
     public:
        RemoteEventHandler(IndexerStubDefault* defaultStub);

        /**
         * Example comment
         */


     private:
        IndexerStubDefault* defaultStub_;
    };
private:
    IndexerStubDefault::RemoteEventHandler remoteEventHandler_;

    /**
     * Example comment
     */
    Indexer::IndexerStatus indexerStatusAttributeValue_;

    CommonAPI::Version interfaceVersion_;
};

} // namespace mediamanager
} // namespace genivi
} // namespace org

#endif // ORG_GENIVI_MEDIAMANAGER_Indexer_STUB_DEFAULT_H_
